# Generated by Django 3.0 on 2021-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210508_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditno', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('monyer', models.IntegerField()),
            ],
        ),
    ]
