# Generated by Django 3.0 on 2021-05-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210512_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
