# Generated by Django 3.0 on 2021-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phoneno', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('Doorno', models.CharField(max_length=10)),
                ('streetname', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
