# Generated by Django 3.0 on 2021-05-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210513_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='itemtype',
            new_name='category',
        ),
    ]
