# Generated by Django 3.0 on 2021-05-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20210522_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='rolerest',
            name='prf',
            field=models.ImageField(max_length=250, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rolerest',
            name='roletype',
            field=models.PositiveIntegerField(choices=[(1, 'customer'), (2, 'seller')]),
        ),
    ]
