# Generated by Django 3.0 on 2021-05-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20210522_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Category'),
        ),
    ]
