# Generated by Django 3.0 on 2021-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20210524_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerest',
            name='prf',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rolerest',
            name='roletype',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'seller')]),
        ),
    ]
