# Generated by Django 3.0 on 2021-05-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20210524_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'customer'), (2, 'seller'), (3, 'guest')], default=3, max_length=10),
        ),
    ]
