# Generated by Django 3.0 on 2021-05-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20210524_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'seller'), (3, 'guest')], default=3),
        ),
    ]
