# Generated by Django 3.0 on 2021-05-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20210524_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerest',
            name='roletype',
            field=models.IntegerField(choices=[(2, 'seller')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'seller')], default=1),
        ),
    ]
