# Generated by Django 3.0 on 2021-05-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20210525_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
