# Generated by Django 3.0 on 2021-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_shippingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qunatity',
            field=models.IntegerField(default=1),
        ),
    ]
