# Generated by Django 3.0 on 2021-05-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_product_qunatity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qunatity',
            field=models.IntegerField(null=True),
        ),
    ]
