# Generated by Django 3.0 on 2021-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_rolerest_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemtype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
