# Generated by Django 3.0 on 2021-05-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_product_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qunatity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
