# Generated by Django 3.0 on 2021-05-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_cart_qunatity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
    ]
