# Generated by Django 3.0 on 2021-05-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_remove_shippingaddress_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
