# Generated by Django 3.0 on 2021-06-01 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_auto_20210601_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cvv',
            field=models.IntegerField(null='True'),
        ),
        migrations.CreateModel(
            name='Myorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('cancel', models.CharField(choices=[('product quality issues', 'product quality issues'), ('I want to change address/phone number', 'I want to change address/phone number'), ('I have purchased product somewhere else', 'I have purchased product somewhere else'), ('others', 'others')], max_length=200, null=True)),
                ('im', models.ImageField(upload_to='')),
                ('is_status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null='True')),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
