# Generated by Django 3.0 on 2021-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_auto_20210601_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='prod',
            field=models.IntegerField(null=True),
        ),
    ]
