# Generated by Django 3.0 on 2021-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_auto_20210602_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='prod',
            field=models.IntegerField(null=True),
        ),
    ]
