# Generated by Django 3.0 on 2021-06-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_orders_prod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
