# Generated by Django 3.0 on 2021-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
