# Generated by Django 3.0 on 2021-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='qunatity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
